"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var fs_1 = require("fs");
var xsd_validator_1 = require("xsd-validator");
var xmlString = (0, fs_1.readFileSync)("./tools/handel.xml", "utf8");
var xmlSchema = (0, fs_1.readFileSync)("./tools/SMOXML.xsd", "utf8");
// const xsdRv = validateSchema(xmlSchema, xsdString);
var xmlRv = (0, xsd_validator_1.default)(xmlString, xmlSchema);
// console.log(xsdRv);
console.log(xmlRv);
